name: Build & Deploy

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci --ignore-scripts
      - run: |
          CI=false NODE_OPTIONS=--openssl-legacy-provider npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/

  deploy-pages:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: build/
      - uses: actions/upload-pages-artifact@v1
        with:
          path: build/
      - id: deployment
        uses: actions/deploy-pages@v1

  deploy-ftp:
    needs: build
    if: ${{ secrets.FTP_HOST != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: build/
      - uses: SamKirkland/FTP-Deploy-Action@4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: build/
          server-dir: public_html/
          dangerous-clean-slate: true
